name: Fetch Champion Data

on:
  workflow_dispatch:

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Fetch champion data
        run: bun run scripts/fetch-champion-data.ts

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push to champion-data branch
        run: |
          # Create a new orphan branch (no history)
          git checkout --orphan champion-data

          # Remove all files from tracking
          git rm -rf .

          # Add only the data files
          git add -f data/*

          # Commit the data
          git commit -m "Update champion data - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

          # Force push to champion-data branch
          git push origin champion-data --force
